export type Any = any;

export const categories: Record<string, string> = {
  machining: 'Machining',
  sheet_metal: 'Sheet metal',
  purchased: 'Purchased',
  other: 'Other',
};

/** Default body colour in the 3D viewer per manufacturing category (uncoated appearance). */
export const categoryColors: Record<string, string> = {
  machining: '#aeb4bc',
  sheet_metal: '#9db0bd',
  purchased: '#7c838c',
  other: '#b3ada2',
};

/** Common RAL Classic colours with approximate sRGB values. */
export const RAL: { code: string; name: string; hex: string }[] = [
  { code: 'RAL 1003', name: 'Signal yellow', hex: '#F9A800' },
  { code: 'RAL 1021', name: 'Rape yellow', hex: '#F3B200' },
  { code: 'RAL 1023', name: 'Traffic yellow', hex: '#FAB500' },
  { code: 'RAL 2004', name: 'Pure orange', hex: '#E25303' },
  { code: 'RAL 2009', name: 'Traffic orange', hex: '#DE5308' },
  { code: 'RAL 3000', name: 'Flame red', hex: '#A72920' },
  { code: 'RAL 3020', name: 'Traffic red', hex: '#BB1E10' },
  { code: 'RAL 4005', name: 'Blue lilac', hex: '#76689A' },
  { code: 'RAL 5002', name: 'Ultramarine blue', hex: '#00387B' },
  { code: 'RAL 5005', name: 'Signal blue', hex: '#005387' },
  { code: 'RAL 5010', name: 'Gentian blue', hex: '#004F7C' },
  { code: 'RAL 5012', name: 'Light blue', hex: '#0089B6' },
  { code: 'RAL 5015', name: 'Sky blue', hex: '#007CB0' },
  { code: 'RAL 5017', name: 'Traffic blue', hex: '#005B8C' },
  { code: 'RAL 6005', name: 'Moss green', hex: '#0F4336' },
  { code: 'RAL 6018', name: 'Yellow green', hex: '#48A43F' },
  { code: 'RAL 6024', name: 'Traffic green', hex: '#008351' },
  { code: 'RAL 6029', name: 'Mint green', hex: '#006F3D' },
  { code: 'RAL 7001', name: 'Silver grey', hex: '#8C969D' },
  { code: 'RAL 7004', name: 'Signal grey', hex: '#9B9B9B' },
  { code: 'RAL 7011', name: 'Iron grey', hex: '#585E63' },
  { code: 'RAL 7012', name: 'Basalt grey', hex: '#5E646A' },
  { code: 'RAL 7015', name: 'Slate grey', hex: '#4F5358' },
  { code: 'RAL 7016', name: 'Anthracite grey', hex: '#383E42' },
  { code: 'RAL 7021', name: 'Black grey', hex: '#2F3234' },
  { code: 'RAL 7024', name: 'Graphite grey', hex: '#45494E' },
  { code: 'RAL 7035', name: 'Light grey', hex: '#C5C7C4' },
  { code: 'RAL 7037', name: 'Dusty grey', hex: '#7A7B7A' },
  { code: 'RAL 7040', name: 'Window grey', hex: '#9EA3A6' },
  { code: 'RAL 7042', name: 'Traffic grey A', hex: '#8E9291' },
  { code: 'RAL 7043', name: 'Traffic grey B', hex: '#4E5451' },
  { code: 'RAL 7045', name: 'Telegrey 1', hex: '#8F9695' },
  { code: 'RAL 7047', name: 'Telegrey 4', hex: '#C8C8C7' },
  { code: 'RAL 8017', name: 'Chocolate brown', hex: '#44322D' },
  { code: 'RAL 9001', name: 'Cream', hex: '#E9E0D2' },
  { code: 'RAL 9002', name: 'Grey white', hex: '#D7D5CB' },
  { code: 'RAL 9003', name: 'Signal white', hex: '#ECECE7' },
  { code: 'RAL 9005', name: 'Jet black', hex: '#0E0E10' },
  { code: 'RAL 9006', name: 'White aluminium', hex: '#A1A1A0' },
  { code: 'RAL 9007', name: 'Grey aluminium', hex: '#878581' },
  { code: 'RAL 9010', name: 'Pure white', hex: '#F1ECE1' },
  { code: 'RAL 9011', name: 'Graphite black', hex: '#27292B' },
  { code: 'RAL 9016', name: 'Traffic white', hex: '#F1F0EA' },
  { code: 'RAL 9017', name: 'Traffic black', hex: '#2A2D2F' },
];

export const suggestions = {
  material: [
    'Mild steel IS 2062 E250 BR',
    'Mild steel IS 513 CR2 (CRCA)',
    'Mild steel HR IS 1079',
    'Stainless steel SS304 (X5CrNi18-10)',
    'Stainless steel SS316L',
    'Aluminium 6061-T6',
    'Aluminium 6082-T6',
    'Aluminium 5052-H32',
    'Alloy steel EN8 (080M40)',
    'Alloy steel EN24 (817M40)',
    'Alloy steel EN19 (709M40)',
    'Bright bar EN1A (230M07)',
    'Cast iron FG260',
    'Brass CZ121 (CuZn39Pb3)',
    'Nylon PA6 (cast)',
    'POM / Delrin',
    'UHMW-PE',
    'Not applicable — purchased part',
  ],
  process: [
    'Laser cutting + CNC bending',
    'Laser cutting',
    'CNC milling (3-axis)',
    'CNC milling (5-axis)',
    'CNC turning',
    'Turn-mill',
    'Sheet metal fabrication + welding',
    'MIG welding fabrication',
    'TIG welding fabrication',
    'Waterjet cutting',
    'Plasma cutting',
    'Wire EDM',
    'Casting + machining',
    'Injection moulding',
    '3D printing (FDM)',
    '3D printing (SLS)',
    'Purchased — no in-house process',
  ],
  operation: [
    'Laser cut',
    'Deburr / edge break',
    'CNC bend',
    'Countersink',
    'Tap threads',
    'PEM insert',
    'Weld',
    'Weld grind',
    'Straighten',
    'CNC mill',
    'CNC turn',
    'Drill',
    'Ream',
    'Bore',
    'Wire EDM',
    'Surface grind',
    'Heat treat',
    'Shot blast',
    'Phosphate',
    'Powder coat',
    'Paint',
    'Anodize',
    'Zinc plate',
    'Passivate',
    'Mask threads / bores',
    'Assemble hardware',
    'Inspect',
    'Mark / label',
    'Pack',
  ],
  finish: [
    'Powder coated',
    'Painted (2K PU)',
    'Zinc plated (Cr3 passivated)',
    'Hot-dip galvanized',
    'Anodized (clear, 15 µm)',
    'Anodized (black, 15 µm)',
    'Black oxide',
    'Electroless nickel',
    'Passivated',
    'Bead blasted',
    'Brushed',
    'Mill finish / as machined',
    'Shot blast + primer',
    'Not applicable',
  ],
  paint: [
    'Powder coat, polyester TGIC-free, 60–80 µm',
    'Powder coat, epoxy-polyester hybrid, 60–80 µm',
    'Powder coat, textured polyester, 80–100 µm',
    'Wet paint, 2K polyurethane, 40–60 µm over epoxy primer',
    'E-coat (cathodic) 20–25 µm',
    'Not applicable',
  ],
  coatingThickness: ['60–80 µm', '80–100 µm', '40–60 µm', '20–25 µm', '15 µm (anodize)', '8–12 µm (zinc)'],
  heat: ['None', 'Stress relieve', 'Normalize', 'Harden & temper 28–32 HRC', 'Harden & temper 40–45 HRC', 'Case harden 0.8 mm, 58–62 HRC', 'Induction harden', 'Solution + age (T6)'],
  hardness: ['As supplied', '28–32 HRC', '40–45 HRC', '58–62 HRC', '180–220 HB', '95 HB (Al 6061-T6)'],
  tolerance: ['ISO 2768-mK', 'ISO 2768-fH', 'ISO 2768-cL', 'ISO 2768-m', 'ISO 13920-B/F (welded)', '±0.1 mm unless noted', '±0.2 mm unless noted', '±0.5 mm unless noted'],
  roughness: ['Ra 0.8', 'Ra 1.6', 'Ra 3.2', 'Ra 6.3', 'Ra 12.5', 'As cut / as bent', 'Not applicable'],
  edge: ['Deburr all edges', 'Break edges 0.2–0.5 × 45°', 'Chamfer 0.5 × 45°', 'Radius R0.5 all edges', 'Grind weld flush', 'Laser edge acceptable'],
  masking: ['None', 'Mask all tapped holes', 'Mask bearing bores', 'Mask ground faces', 'Mask earth points'],
  marking: ['None', 'Laser etch part number + revision', 'Stamp part number', 'Label sticker with part number', 'Engrave serial number'],
  packaging: ['Individually bubble-wrapped', 'Bulk in crate, separated by foam', 'VCI paper + carton', 'Pallet, strapped', 'As per vendor standard'],
  stock: ['Sheet 1.5 mm', 'Sheet 2.0 mm', 'Sheet 3.0 mm', 'Plate 6 mm', 'Plate 10 mm', 'Plate 12 mm', 'Round bar Ø25', 'Round bar Ø40', 'Square tube 40×40×3', 'Rectangular tube 60×40×3', 'Angle 40×40×5', 'Billet (see envelope)'],
};

export const date = (s: string) =>
  new Date(s).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });
export const fmt = (x: number) => Number(x || 0).toLocaleString(undefined, { maximumFractionDigits: 3 });
